import { Inter, Josefin_Sans } from 'next/font/google'
import './globals.css'

const Josefin = Josefin_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Josefin.className}>
      <h1 className="text-7xl text-center mt-10">RandomRhythm</h1>
      {children}
      </body>
    </html>
  )
}
