import { Josefin_Sans } from 'next/font/google'
import { MetronomeProvider } from '@/contexts/MetronomeContext';
import './globals.css'

const Josefin = Josefin_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MetronomeProvider>
          <body className={Josefin.className}>
          <h1 className="mt-10 text-center text-7xl text-slate-800">RandomRhythm</h1>
          {children}
          </body>
      </MetronomeProvider>
    </html>
  )
}
